///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

using IronOcr;

namespace Zoom_Web
{
    public partial class ClearBtn
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void DoOCR()
        {
        }

        public void Mouse_DoubleClick_Clear(RepoItemInfo inputtagInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'inputtagInfo' at 23;9.", inputtagInfo);
            inputtagInfo.FindAdapter<InputTag>().DoubleClick();
            
            if(inputtagInfo.Exists())
            {
            	
            }
        }

        public void Mouse_Click_List1(RepoItemInfo listInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'listInfo' at Center.", listInfo);
            listInfo.FindAdapter<List>().Click();
        }

    }
}
