///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Zoom_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragNDrop recording.
    /// </summary>
    [TestModule("b0cf2fd8-a691-47e4-9c1d-dd8826ff507f", ModuleType.Recording, 1)]
    public partial class DragNDrop : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Zoom_WebRepository repository.
        /// </summary>
        public static Zoom_WebRepository repo = Zoom_WebRepository.Instance;

        static DragNDrop instance = new DragNDrop();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragNDrop()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragNDrop Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Textboxes.FirstName' at Center.", repo.ApplicationUnderTest.Textboxes.FirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Textboxes.FirstName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mubin' with focus on 'ApplicationUnderTest.Textboxes.FirstName'.", repo.ApplicationUnderTest.Textboxes.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Textboxes.FirstName.PressKeys("mubin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Kadiwala' with focus on 'ApplicationUnderTest.Textboxes.LastName'.", repo.ApplicationUnderTest.Textboxes.LastNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Textboxes.LastName.PressKeys("Kadiwala");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
