///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Zoom_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("be601fb3-6e6e-4e77-aff1-caaf5a24ee23", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Zoom_WebRepository repository.
        /// </summary>
        public static Zoom_WebRepository repo = Zoom_WebRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            MyCMD = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _MyCMD;

        /// <summary>
        /// Gets or sets the value of variable MyCMD.
        /// </summary>
        [TestVariable("ca14c79d-0d4e-43a4-b3bc-0f51db73980a")]
        public string MyCMD
        {
            get { return _MyCMD; }
            set { _MyCMD = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable ToolBarIcon.
        /// </summary>
        [TestVariable("aa7871c6-ef2a-43f4-8160-b33c6b94e881")]
        public string ToolBarIcon
        {
            get { return repo.ToolBarIcon; }
            set { repo.ToolBarIcon = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TextEditors.TextArea' at 428;201.", repo.TextEditors.TextAreaInfo, new RecordItemIndex(0));
            repo.TextEditors.TextArea.Click("428;201");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'TextEditors.TextArea' and assigning its value to variable 'MyCMD'.", repo.TextEditors.TextAreaInfo, new RecordItemIndex(1));
            MyCMD = repo.TextEditors.TextArea.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", MyCMD, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TextEditors.Document1Word.Draw' at Center.", repo.TextEditors.Document1Word.DrawInfo, new RecordItemIndex(3));
            repo.TextEditors.Document1Word.Draw.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
