///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Zoom_Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Zoom_WebRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f8f1425a-18c7-4bec-ab85-dad776bea586")]
    public partial class Zoom_WebRepository : RepoGenBaseFolder
    {
        static Zoom_WebRepository instance = new Zoom_WebRepository();
        Zoom_WebRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Zoom_WebRepositoryFolders.ExplorerAppFolder _explorer;
        Zoom_WebRepositoryFolders.CommandPromptAppFolder _commandprompt;
        Zoom_WebRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        Zoom_WebRepositoryFolders.TextEditorsFolder _texteditors;

        /// <summary>
        /// Gets the singleton class instance representing the Zoom_WebRepository element repository.
        /// </summary>
        [RepositoryFolder("f8f1425a-18c7-4bec-ab85-dad776bea586")]
        public static Zoom_WebRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Zoom_WebRepository() 
            : base("Zoom_WebRepository", "/", null, 0, false, "f8f1425a-18c7-4bec-ab85-dad776bea586", ".\\RepositoryImages\\Zoom_WebRepositoryf8f1425a.rximgres")
        {
            _applicationundertest = new Zoom_WebRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _explorer = new Zoom_WebRepositoryFolders.ExplorerAppFolder(this);
            _commandprompt = new Zoom_WebRepositoryFolders.CommandPromptAppFolder(this);
            _rxmainframe = new Zoom_WebRepositoryFolders.RxMainFrameAppFolder(this);
            _texteditors = new Zoom_WebRepositoryFolders.TextEditorsFolder(this);
        }

#region Variables

        string _Gender = "male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("a8697a7f-c843-4657-8fc6-f5dc55d78c07")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _Category = "";

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("d4522317-ea8b-4b4c-907f-5fa79996d47f")]
        public string Category
        {
            get { return _Category; }
            set { _Category = value; }
        }

        string _ToolBarIcon = "Draw";

        /// <summary>
        /// Gets or sets the value of variable ToolBarIcon.
        /// </summary>
        [TestVariable("aa7871c6-ef2a-43f4-8160-b33c6b94e881")]
        public string ToolBarIcon
        {
            get { return _ToolBarIcon; }
            set { _ToolBarIcon = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f8f1425a-18c7-4bec-ab85-dad776bea586")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("1a8b9069-9025-466f-9260-51966608bd1a")]
        public virtual Zoom_WebRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("5cc4f28d-475f-4ac2-9444-fe7dc7e9a1b0")]
        public virtual Zoom_WebRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The CommandPrompt folder.
        /// </summary>
        [RepositoryFolder("e3e417b1-665b-4d76-b536-a3cb08a30b3d")]
        public virtual Zoom_WebRepositoryFolders.CommandPromptAppFolder CommandPrompt
        {
            get { return _commandprompt; }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("f1101d9f-dd02-483e-8270-12bd297437a4")]
        public virtual Zoom_WebRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The TextEditors folder.
        /// </summary>
        [RepositoryFolder("929a9e26-57d7-463b-87a8-fb8e64391020")]
        public virtual Zoom_WebRepositoryFolders.TextEditorsFolder TextEditors
        {
            get { return _texteditors; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Zoom_WebRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a8b9069-9025-466f-9260-51966608bd1a")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Zoom_WebRepositoryFolders.TextboxesFolder _textboxes;
            Zoom_WebRepositoryFolders.ButtonsFolder _buttons;
            RepoItemInfo _categoryInfo;
            RepoItemInfo _clearInfo;
            RepoItemInfo _gender1Info;
            RepoItemInfo _someptagInfo;
            RepoItemInfo _countInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "1a8b9069-9025-466f-9260-51966608bd1a", "")
            {
                _textboxes = new Zoom_WebRepositoryFolders.TextboxesFolder(this);
                _buttons = new Zoom_WebRepositoryFolders.ButtonsFolder(this);
                _categoryInfo = new RepoItemInfo(this, "Category", ".//select[#'Category']/option[@value=$Category]", "", 30000, null, "3505c258-071a-4b51-87fc-85b79e96f2f4");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", "", 30000, null, "e48c22f1-e29d-40e1-93c4-b703effa7bfb");
                _gender1Info = new RepoItemInfo(this, "Gender1", ".//td[#'gender']/table//input[@id='Gender']", "", 30000, null, "e349efc6-8536-4447-9668-1b6966726eb5");
                _someptagInfo = new RepoItemInfo(this, "SomePTag", ".//div[#'et_builder_outer_content']/div/div[2]/div/div/div[2]/?/?/p", "", 30000, null, "3c8a83cb-536d-4559-aa23-fb16ea5354d9");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", "", 30000, null, "df4d0744-b5a1-4359-8535-97a79dbb81c7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a8b9069-9025-466f-9260-51966608bd1a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a8b9069-9025-466f-9260-51966608bd1a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Category item.
            /// </summary>
            [RepositoryItem("3505c258-071a-4b51-87fc-85b79e96f2f4")]
            public virtual Ranorex.OptionTag Category
            {
                get
                {
                    return _categoryInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Category item info.
            /// </summary>
            [RepositoryItemInfo("3505c258-071a-4b51-87fc-85b79e96f2f4")]
            public virtual RepoItemInfo CategoryInfo
            {
                get
                {
                    return _categoryInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("e48c22f1-e29d-40e1-93c4-b703effa7bfb")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("e48c22f1-e29d-40e1-93c4-b703effa7bfb")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }

            /// <summary>
            /// The Gender1 item.
            /// </summary>
            [RepositoryItem("e349efc6-8536-4447-9668-1b6966726eb5")]
            public virtual Ranorex.InputTag Gender1
            {
                get
                {
                    return _gender1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender1 item info.
            /// </summary>
            [RepositoryItemInfo("e349efc6-8536-4447-9668-1b6966726eb5")]
            public virtual RepoItemInfo Gender1Info
            {
                get
                {
                    return _gender1Info;
                }
            }

            /// <summary>
            /// The SomePTag item.
            /// </summary>
            [RepositoryItem("3c8a83cb-536d-4559-aa23-fb16ea5354d9")]
            public virtual Ranorex.PTag SomePTag
            {
                get
                {
                    return _someptagInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The SomePTag item info.
            /// </summary>
            [RepositoryItemInfo("3c8a83cb-536d-4559-aa23-fb16ea5354d9")]
            public virtual RepoItemInfo SomePTagInfo
            {
                get
                {
                    return _someptagInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("df4d0744-b5a1-4359-8535-97a79dbb81c7")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("df4d0744-b5a1-4359-8535-97a79dbb81c7")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Textboxes folder.
            /// </summary>
            [RepositoryFolder("e06da471-4a25-4cab-9daf-736eaaa8acdf")]
            public virtual Zoom_WebRepositoryFolders.TextboxesFolder Textboxes
            {
                get { return _textboxes; }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("a69a4c7e-bcc9-40e3-a0ba-6e23068b5fbc")]
            public virtual Zoom_WebRepositoryFolders.ButtonsFolder Buttons
            {
                get { return _buttons; }
            }
        }

        /// <summary>
        /// The TextboxesFolder folder.
        /// </summary>
        [RepositoryFolder("e06da471-4a25-4cab-9daf-736eaaa8acdf")]
        public partial class TextboxesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;

            /// <summary>
            /// Creates a new Textboxes  folder.
            /// </summary>
            public TextboxesFolder(RepoGenBaseFolder parentFolder) :
                    base("Textboxes", "", parentFolder, 0, null, false, "e06da471-4a25-4cab-9daf-736eaaa8acdf", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", "", 30000, null, "f6da38e8-0dd8-4910-a85e-1ac555f24215");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", "", 30000, null, "eca5fd42-763f-4770-a7b5-e91bc42de344");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e06da471-4a25-4cab-9daf-736eaaa8acdf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f6da38e8-0dd8-4910-a85e-1ac555f24215")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f6da38e8-0dd8-4910-a85e-1ac555f24215")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("eca5fd42-763f-4770-a7b5-e91bc42de344")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("eca5fd42-763f-4770-a7b5-e91bc42de344")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }
        }

        /// <summary>
        /// The ButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("a69a4c7e-bcc9-40e3-a0ba-6e23068b5fbc")]
        public partial class ButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 30000, null, false, "a69a4c7e-bcc9-40e3-a0ba-6e23068b5fbc", "")
            {
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@value=$Gender]", "", 30000, null, "06b2912a-abfc-4d4c-ac0c-6f7da52b8daf");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", "", 30000, null, "0309b42a-ecf9-4e7d-b25b-1e7b471fbbca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a69a4c7e-bcc9-40e3-a0ba-6e23068b5fbc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a69a4c7e-bcc9-40e3-a0ba-6e23068b5fbc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("06b2912a-abfc-4d4c-ac0c-6f7da52b8daf")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("06b2912a-abfc-4d4c-ac0c-6f7da52b8daf")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("0309b42a-ecf9-4e7d-b25b-1e7b471fbbca")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("0309b42a-ecf9-4e7d-b25b-1e7b471fbbca")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("5cc4f28d-475f-4ac2-9444-fe7dc7e9a1b0")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _list1Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "5cc4f28d-475f-4ac2-9444-fe7dc7e9a1b0", "")
            {
                _list1Info = new RepoItemInfo(this, "List1", "?/?/list[@controlid='1']", "", 30000, null, "cc8dc8f8-7903-4a3a-b449-e7c04fe8f986");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5cc4f28d-475f-4ac2-9444-fe7dc7e9a1b0")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5cc4f28d-475f-4ac2-9444-fe7dc7e9a1b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List1 item.
            /// </summary>
            [RepositoryItem("cc8dc8f8-7903-4a3a-b449-e7c04fe8f986")]
            public virtual Ranorex.List List1
            {
                get
                {
                    return _list1Info.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The List1 item info.
            /// </summary>
            [RepositoryItemInfo("cc8dc8f8-7903-4a3a-b449-e7c04fe8f986")]
            public virtual RepoItemInfo List1Info
            {
                get
                {
                    return _list1Info;
                }
            }
        }

        /// <summary>
        /// The CommandPromptAppFolder folder.
        /// </summary>
        [RepositoryFolder("e3e417b1-665b-4d76-b536-a3cb08a30b3d")]
        public partial class CommandPromptAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CommandPrompt  folder.
            /// </summary>
            public CommandPromptAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CommandPrompt", "/form[@title='Command Prompt']", parentFolder, 30000, null, true, "e3e417b1-665b-4d76-b536-a3cb08a30b3d", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e3e417b1-665b-4d76-b536-a3cb08a30b3d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e3e417b1-665b-4d76-b536-a3cb08a30b3d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1101d9f-dd02-483e-8270-12bd297437a4")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "f1101d9f-dd02-483e-8270-12bd297437a4", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/tabpage[@controlname='RxTabStandard']/?/?/text[@accessiblename='First name']", "", 30000, null, "0c1d0e59-080a-4cc8-8234-cb3d433b9877");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1101d9f-dd02-483e-8270-12bd297437a4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1101d9f-dd02-483e-8270-12bd297437a4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("0c1d0e59-080a-4cc8-8234-cb3d433b9877")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("0c1d0e59-080a-4cc8-8234-cb3d433b9877")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }
        }

        /// <summary>
        /// The TextEditorsFolder folder.
        /// </summary>
        [RepositoryFolder("929a9e26-57d7-463b-87a8-fb8e64391020")]
        public partial class TextEditorsFolder : RepoGenBaseFolder
        {
            Zoom_WebRepositoryFolders.Document1WordAppFolder _document1word;
            RepoItemInfo _textareaInfo;

            /// <summary>
            /// Creates a new TextEditors  folder.
            /// </summary>
            public TextEditorsFolder(RepoGenBaseFolder parentFolder) :
                    base("TextEditors", "", parentFolder, 0, null, false, "929a9e26-57d7-463b-87a8-fb8e64391020", "")
            {
                _document1word = new Zoom_WebRepositoryFolders.Document1WordAppFolder(this);
                _textareaInfo = new RepoItemInfo(this, "TextArea", "/form[@title~'Command Prompt']/text[@automationid='Text Area']", "", 30000, null, "308791bd-d8db-4ea9-ab86-270dbe4a087c");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("929a9e26-57d7-463b-87a8-fb8e64391020")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TextArea item.
            /// </summary>
            [RepositoryItem("308791bd-d8db-4ea9-ab86-270dbe4a087c")]
            public virtual Ranorex.Text TextArea
            {
                get
                {
                    return _textareaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextArea item info.
            /// </summary>
            [RepositoryItemInfo("308791bd-d8db-4ea9-ab86-270dbe4a087c")]
            public virtual RepoItemInfo TextAreaInfo
            {
                get
                {
                    return _textareaInfo;
                }
            }

            /// <summary>
            /// The Document1Word folder.
            /// </summary>
            [RepositoryFolder("19d8deee-f9fb-4d84-9867-a4158dddf652")]
            public virtual Zoom_WebRepositoryFolders.Document1WordAppFolder Document1Word
            {
                get { return _document1word; }
            }
        }

        /// <summary>
        /// The Document1WordAppFolder folder.
        /// </summary>
        [RepositoryFolder("19d8deee-f9fb-4d84-9867-a4158dddf652")]
        public partial class Document1WordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _drawInfo;
            RepoItemInfo _designInfo;

            /// <summary>
            /// Creates a new Document1Word  folder.
            /// </summary>
            public Document1WordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Document1Word", "/form[@title='Document1 - Word']", parentFolder, 30000, null, true, "19d8deee-f9fb-4d84-9867-a4158dddf652", "")
            {
                _drawInfo = new RepoItemInfo(this, "Draw", ".//tabpage[@name=$ToolBarIcon]", "", 30000, null, "5802fbb1-11dc-41c0-8811-4801007cedcd");
                _designInfo = new RepoItemInfo(this, "Design", "container[@caption='MsoDockTop']//container[@name='Ribbon']/tabpagelist[@name='Ribbon Tabs']/tabpagehome[@name='Design']", "", 30000, null, "ec4cc33e-23b5-475d-9ccf-d6d5dcefe0f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19d8deee-f9fb-4d84-9867-a4158dddf652")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19d8deee-f9fb-4d84-9867-a4158dddf652")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Draw item.
            /// </summary>
            [RepositoryItem("5802fbb1-11dc-41c0-8811-4801007cedcd")]
            public virtual Ranorex.TabPage Draw
            {
                get
                {
                    return _drawInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Draw item info.
            /// </summary>
            [RepositoryItemInfo("5802fbb1-11dc-41c0-8811-4801007cedcd")]
            public virtual RepoItemInfo DrawInfo
            {
                get
                {
                    return _drawInfo;
                }
            }

            /// <summary>
            /// The Design item.
            /// </summary>
            [RepositoryItem("ec4cc33e-23b5-475d-9ccf-d6d5dcefe0f2")]
            public virtual Ranorex.Unknown Design
            {
                get
                {
                    return _designInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Design item info.
            /// </summary>
            [RepositoryItemInfo("ec4cc33e-23b5-475d-9ccf-d6d5dcefe0f2")]
            public virtual RepoItemInfo DesignInfo
            {
                get
                {
                    return _designInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
